var bingoList = [];
bingoList[1] = [
	{ name: "Terrorist attack", types: ["normal"]},
	{ name: "Booing", types: ["normal"]},
	{ name: "Samba Dancing", types: ["normal"]},
	{ name: "Meme Magic", types: ["normal"]},
	{ name: "Police shooting", types: ["normal"]},
	{ name: "Native Indians Appears", types: ["normal"]},
	{ name: "A new Meme is born", types: ["normal"]},
	{ name: "Carnival", types: ["normal"]},
	{ name: "BUNDA! (Ass)", types: ["normal"]},
	{ name: "Refugees appears", types: ["normal"]},
	{ name: "Ceremony gets interupted", types: ["normal"]},
	{ name: "Power outage", types: ["normal"]},
	{ name: "Assasination", types: ["normal"]},
	{ name: "Dilma Rousseff appears", types: ["normal"]},
	{ name: "Engineering catastrophe", types: ["normal"]},
	{ name: "Live animals", types: ["normal"]},
	{ name: "Someting sets on fire", types: ["normal"]},
	{ name: "Protesters", types: ["normal"]},
	{ name: "Reports of sexual assaults", types: ["normal"]},
	{ name: "Athlete(s) dies", types: ["normal"]},
	{ name: "Fireworks disaster", types: ["normal"]},
	{ name: "/pol/ gets triggered", types: ["normal"]},
	{ name: "BOPE appears", types: ["normal"]},
	{ name: "Spectator(s) dies", types: ["normal"]},
	{ name: "Bomb explodes", types: ["normal"]},
	{ name: "Drone crashes on athlete or audience", types: ["normal"]},
	{ name: "Athlete is seriously ill after swimming in water", types: ["normal"]},
	{ name: "Stray dogs roam Olympic grounds", types: ["normal"]},
	{ name: "Visitor/staff reported positive for Zika", types: ["normal"]},
	{ name: "Athlete kidnapped", types: ["normal"]},
];

$(function() { srl.bingo(bingoList, 5); });
